#这个文件的配置公用的
spring:
  profiles:
    active: prod

  ############### 数据源的相关配置###################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf-8
    username: root
    password: 123

  ############### JPA的相关配置###################
  jpa:
    #显示SQL语句
    show-sql: true
    hibernate:
      # 自动创建表，每次运行都会创建新表，如果已经存在则会首先删除
      # ddl-auto: create
      # 自动创建表，如果表已经存在表中有数据，则不会重建
      ddl-auto: update

  ################ Freemarker的静态配置##############
  #  设置FTL文件路径
  freemarker:
    template-loader-path: classpath:/templates
    #  关闭缓存，及时刷新，上线生产环境需要改为true
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  ################ Thymeleaf的静态配置##############
  # prefix 的配置值 /templates/  一定要有后面的/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false

  ################ 热部署#############################
  devtools:
    #排除devtools因为静态资源改变而重启
    restart:
      enabled: true
      #设置重启的目录，添加那个目录的文件需要restart
      additional-paths: src/main/java
      additional-exclude: static/**,public/**
      # 修改文件夹内容不需要重启的目录
      exclude: WEB-INF/**

  ################# JSON相关配置########################
  #搜索得到的配置，解决返回对象报错问题https://www.zhihu.com/question/267864644/answer/330572239
  jackson:
    serialization:
      fail-on-empty-beans: false

  ################# MVC相关配置#########################
  mvc:
    static-path-pattern: /static/**

  ################# i18n资源配置########################
  messages:
    basename: classpath:i18n/book
    cache-duration:
    encoding: UTF-8

##############S erver服务端的相关配置####################
#  配置端口号以及访问路径
server:
  port: 8080
  servlet:
    #    context-path: /spring
    session:
      timeout:
  error:
    path: /error
  # 编码配置
  tomcat:
    uri-encoding: UTF-8
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true




