#配置默认访问端口以及访问路径
server:
  port: 8080

#logging:
#  pattern:
#    console: "%d - %msg%n"
#    path: log/
#  #  file: log/sell.log
#  level:
#    #指定总体日志级别
#    root: debug
#    #指定类的日志级别
#    net.codingme.boot.LoggerTest2: error
